const menu = [
	{
	  id: 1,
	  title: 'buttermilk pancakes',
	  category: 'psd design',
	  img: '../../../images/item-4.jpeg',
	  desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
	},
	{
	  id: 2,
	  title: 'diner double',
	  category: 'psd design',
	  img: '../../../images/item-4.jpeg',
	  desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
	},
	{
	  id: 3,
	  title: 'godzilla milkshake',
	  category: 'presentation',
	  img: '../../../images/item-4.jpeg',
	  desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
	},
	{
	  id: 4,
	  title: 'country delight',
	  category: 'work ideas',
	  img: '../../../images/item-4.jpeg',
	  desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
	},
	{
	  id: 5,
	  title: 'egg attack',
	  category: 'mock up',
	  img: '../../../images/item-5.jpeg',
	  desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
	},
	{
	  id: 6,
	  title: 'oreo dream',
	  category: 'logo',
	  img: '../../../images/item-6.jpeg',
	  desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
	},
	{
	  id: 7,
	  title: 'bacon overflow',
	  category: 'icons',
	  img: '../../../images/item-7.jpeg',
	  desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
	},
	{
	  id: 8,
	  title: 'american classic',
	  category: 'psd design',
	  img: '../../../images/item-8.jpeg',
	  desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
	},
	{
	  id: 9,
	  title: 'quarantine buddy',
	  category: 'presentation',
	  img: '../../../images/item-9.jpeg',
	  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	},
	{
		id: 10,
		title: 'quarantine buddy',
		category: 'work ideas',
		img: '../../../images/item-9.jpeg',
		desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	},
	{
		id: 11,
		title: 'quarantine buddy',
		category: 'mock up',
		img: '../../../images/item-9.jpeg',
		desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	},
	{
		id: 12,
		title: 'quarantine buddy',
		category: 'logo',
		img: '../../../images/item-9.jpeg',
		desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	},
	{
		id: 13,
		title: 'quarantine buddy',
		category: 'icons',
		img: '../../../images/item-9.jpeg',
		desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	},
	{
		id: 14,
		title: 'quarantine buddy',
		category: 'icons',
		img: '../../../images/item-9.jpeg',
		desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	},
	{
		id: 15,
		title: 'buttermilk pancakes',
		category: 'psd',
		img: '../../../images/item-6.jpeg',
		desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
	  },
	  {
		id: 16,
		title: 'diner double',
		category: 'psd design',
		img: '../../../images/item-4.jpeg',
		desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
	  },
	  {
		id: 17,
		title: 'godzilla milkshake',
		category: 'presentation',
		img: '../../../images/item-2.jpeg',
		desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
	  },
	  {
		id: 18,
		title: 'country delight',
		category: 'work ideas',
		img: '../../../images/item-4.jpeg',
		desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
	  },
	  {
		id: 19,
		title: 'egg attack',
		category: 'mock up',
		img: '../../../images/item-5.jpeg',
		desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
	  },
	  {
		id: 20,
		title: 'oreo dream',
		category: 'logo',
		img: '../../../images/item-6.jpeg',
		desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
	  },
	  {
		id: 21,
		title: 'bacon overflow',
		category: 'icons',
		img: '../../../images/item-7.jpeg',
		desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
	  },
	  {
		id: 22,
		title: 'american classic',
		category: 'psd design',
		img: '../../../images/item-8.jpeg',
		desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
	  },
	  {
		id: 23,
		title: 'quarantine buddy',
		category: 'presentation',
		img: '../../../images/item-9.jpeg',
		desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		  id: 24,
		  title: 'quarantine buddy',
		  category: 'work ideas',
		  img: '../../../images/item-9.jpeg',
		  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		  id: 25,
		  title: 'quarantine buddy',
		  category: 'mock up',
		  img: '../../../images/item-9.jpeg',
		  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		  id: 26,
		  title: 'quarantine buddy',
		  category: 'logo',
		  img: '../../../images/item-9.jpeg',
		  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		  id: 27,
		  title: 'quarantine buddy',
		  category: 'icons',
		  img: '../../../images/item-9.jpeg',
		  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		  id: 28,
		  title: 'quarantine buddy',
		  category: 'icons',
		  img: '../../../images/item-9.jpeg',
		  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		id: 29,
		title: 'buttermilk pancakes',
		category: 'psd',
		img: '../../../images/item-5.jpeg',
		desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
	  },
	  {
		id: 30,
		title: 'diner double',
		category: 'psd design',
		img: '../../../images/item-7.jpeg',
		desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
	  },
	  {
		id: 31,
		title: 'godzilla milkshake',
		category: 'presentation',
		img: '../../../images/item-4.jpeg',
		desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
	  },
	  {
		id: 34,
		title: 'country delight',
		category: 'work ideas',
		img: '../../../images/item-4.jpeg',
		desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
	  },
	  {
		id: 35,
		title: 'egg attack',
		category: 'mock up',
		img: '../../../images/item-5.jpeg',
		desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
	  },
	  {
		id: 36,
		title: 'oreo dream',
		category: 'logo',
		img: '../../../images/item-6.jpeg',
		desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
	  },
	  {
		id: 37,
		title: 'bacon overflow',
		category: 'icons',
		img: '../../../images/item-7.jpeg',
		desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
	  },
	  {
		id: 38,
		title: 'american classic',
		category: 'psd design',
		img: '../../../images/item-8.jpeg',
		desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
	  },
	  {
		id: 39,
		title: 'quarantine buddy',
		category: 'presentation',
		img: '../../../images/item-9.jpeg',
		desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		  id: 40,
		  title: 'quarantine buddy',
		  category: 'work ideas',
		  img: '../../../images/item-9.jpeg',
		  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		  id: 41,
		  title: 'quarantine buddy',
		  category: 'mock up',
		  img: '../../../images/item-9.jpeg',
		  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		  id: 42,
		  title: 'quarantine buddy',
		  category: 'logo',
		  img: '../../../images/item-9.jpeg',
		  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		  id: 43,
		  title: 'quarantine buddy',
		  category: 'icons',
		  img: '../../../images/item-9.jpeg',
		  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		  id: 44,
		  title: 'quarantine buddy',
		  category: 'icons',
		  img: '../../../images/item-9.jpeg',
		  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	  },
	  {
		  id: 45,
		  title: 'buttermilk pancakes',
		  category: 'psd',
		  img: '../../../images/item-4.jpeg',
		  desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
		},
		{
		  id: 46,
		  title: 'diner double',
		  category: 'psd design',
		  img: '../../../images/item-4.jpeg',
		  desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
		},
		{
		  id: 47,
		  title: 'godzilla milkshake',
		  category: 'presentation',
		  img: '../../../images/item-4.jpeg',
		  desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
		},
		{
		  id: 48,
		  title: 'country delight',
		  category: 'work ideas',
		  img: '../../../images/item-4.jpeg',
		  desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
		},
		{
		  id: 49,
		  title: 'egg attack',
		  category: 'mock up',
		  img: '../../../images/item-5.jpeg',
		  desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
		},
		{
		  id: 50,
		  title: 'oreo dream',
		  category: 'logo',
		  img: '../../../images/item-6.jpeg',
		  desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
		},
		{
		  id: 51,
		  title: 'bacon overflow',
		  category: 'icons',
		  img: '../../../images/item-7.jpeg',
		  desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
		},
		{
		  id: 52,
		  title: 'american classic',
		  category: 'psd design',
		  img: '../../../images/item-8.jpeg',
		  desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
		},
		{
		  id: 53,
		  title: 'quarantine buddy',
		  category: 'presentation',
		  img: '../../../images/item-9.jpeg',
		  desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
		},
		{
			id: 54,
			title: 'quarantine buddy',
			category: 'work ideas',
			img: '../../../images/item-9.jpeg',
			desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
		},
		{
			id: 55,
			title: 'quarantine buddy',
			category: 'mock up',
			img: '../../../images/item-9.jpeg',
			desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
		},
		{
			id: 56,
			title: 'quarantine buddy',
			category: 'logo',
			img: '../../../images/item-9.jpeg',
			desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
		},
		{
			id: 57,
			title: 'quarantine buddy',
			category: 'icons',
			img: '../../../images/item-9.jpeg',
			desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
		},
		{
			id: 58,
			title: 'quarantine buddy',
			category: 'icons',
			img: '../../../images/item-9.jpeg',
			desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
		},
  ];
  export default menu;
  